---
name: Publish Web Artifacts

# yamllint disable rule:truthy
on:
    pull_request:
        types: [closed]
        branches: ["main"]
        paths:
            - 'web/**'
    workflow_dispatch:

permissions:
    contents: read

concurrency:
    group: publish-web
    cancel-in-progress: false

# yamllint disable rule:line-length
jobs:
    publish_web:
        name: Publish Web Artifacts
        if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            - name: Checkout code
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
              id: checkout
              with:
                  persist-credentials: false

            - name: Upload to AWS S3
              id: upload_web
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
                  AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
              run: |
                  aws s3 sync ./web/html "s3://${AWS_BUCKET}/" --no-progress --cache-control no-cache
                  aws s3 sync ./web/css "s3://${AWS_BUCKET}/css/" --no-progress --cache-control no-cache
